name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-java@v4
        name: Set up JDK 17
        with:
          java-version: 17
          distribution: adopt-hotspot
      - name: Build plugin
        run: |
          chmod +x gradlew
          ./gradlew check buildPlugin signPlugin --info
      - name: Upload built plugin
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: build/distributions/*.zip
